# filepath: /Users/rvb/Library/Mobile Documents/com~apple~CloudDocs/Developer/my-assistant/my-assistant/Website/Dockerfile
FROM python:3.9-slim

WORKDIR /app

COPY src/ /app

CMD ["python3", "-m", "http.server", "8080"]