version: '3.8'

services:
  app:
    build: ./app
    volumes:
      - ./app:/app
    expose:
      - "8080"

  # service1:
  #   build: ./services/service1
  #   expose:
  #     - "5001"

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
      # - service1