version: '3.8'

services:
  app:
    build: ./app
    volumes:
      - ./app:/app
    expose:
      - "8080"
    networks:
      - app_network

  base_chat:
    build: ./services/base_chat
    ports:
      - "3000:3000"
    networks:
      - app_network
  


  html_service:
    build: ./services/html_service
    ports:
      - "5003:3001"
    networks:
      - app_network

  

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /etc/nginx/ssl-dhparams.pem:/etc/nginx/ssl-dhparams.pem:ro
    depends_on:
      - app
      - base_chat
      - html_service
    networks:
      - app_network

networks:
  app_network:
    driver: bridge